---
title: "Bin_analysis"
author: "Ruben Props"
date: "August 17 2017"
output:
  html_document:
    code_folding: show
    highlight: haddock
    keep_md: yes
    theme: united
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
      toc_depth: 2
    css: report_styles.css
---


```{r setup, include = FALSE, warning = FALSE}
knitr::opts_chunk$set(eval = TRUE, 
                      echo = TRUE, 
                      cache = TRUE,
                      include = TRUE,
                      collapse = FALSE,
                      dependson = NULL,
                      engine = "R", # Chunks will always have R code, unless noted
                      error = TRUE,
                      fig.path="Figures/cached/",  # Set the figure options
                      fig.align = "center"
                      )
library("dplyr")
library("ggplot2")
library("grid")
library("gridExtra")
source("functions.R")
```

# Genome characteristics

Import genome characteristics and binning statistics from anvi'o output:

```{r visualize-binning-statistics, warning = FALSE, fig.width = 10, fig.height = 7.5}
# Import anvi'o data
df_stats <- read.table("./anvio_output/general_bins_summary_selected_final.tsv", sep ="\t",
           header = TRUE, blank.lines.skip = TRUE, skipNul = TRUE)

# Also import more correct taxonomic classification from Phylosift
df_tax <- read.table("./anvio_output/bin_classification_phylosift.tsv", sep ="\t",
           header = TRUE, blank.lines.skip = TRUE, skipNul = TRUE)

# Merge both dataframes
df_merge <- dplyr::inner_join(df_stats, df_tax, by = c("bins" = "Bin"))
print(df_merge)

# Completeness estimate
p1 <- ggplot(data = df_merge, aes(x = bins, y = percent_complete, fill = Classification, shape = taxon))+
  geom_point(size = 4)+
  theme_bw()+
  ylim(0,100)+
  theme(axis.text.x = element_text(angle = 60, hjust = 1),
        axis.text=element_text(size=14), axis.title=element_text(size=20),
        title=element_text(size=20), legend.text=element_text(size=16))+
  guides(fill = guide_legend(override.aes = list(shape = 22)))+
  geom_hline(yintercept = 75)+
  scale_fill_brewer(palette = "Accent")+
  scale_shape_manual(values = c(21,22,23,24))

# Observed genome size
p2 <- ggplot(data = df_merge, aes(x = bins, y = total_length, fill = Classification, shape = taxon))+
  geom_point(size = 4)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 60, hjust = 1),
        axis.text=element_text(size=14), axis.title=element_text(size=20),
        title=element_text(size=20), legend.text=element_text(size=16))+
  scale_fill_brewer(palette = "Accent")+
  ylim(0, 3.1e6)+
  scale_shape_manual(values = c(21,22,23,24))

# Estimated genome size
p3 <- ggplot(data = df_merge, aes(x = bins, y = total_length*percent_complete/100, fill = Classification, shape = taxon))+
  geom_point(size = 4)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 60, hjust = 1),
        axis.text=element_text(size=14), axis.title=element_text(size=20),
        title=element_text(size=20), legend.text=element_text(size=16))+
  scale_fill_brewer(palette = "Accent")+
  scale_shape_manual(values = c(21,22,23,24))

# Contamination plot
p4 <- ggplot(data = df_merge, aes(x = bins, y = percent_redundancy, fill = Classification, shape = taxon))+
  geom_point(size = 4)+
  theme_bw()+
  ylim(0,10)+
  theme(axis.text.x = element_text(angle = 60, hjust = 1),
        axis.text=element_text(size=14), axis.title=element_text(size=20),
        title=element_text(size=20), legend.text=element_text(size=16))+
  scale_fill_brewer(palette = "Accent")+
  scale_shape_manual(values = c(21,22,23,24))

# GC content
p5 <- ggplot(data = df_merge, aes(x = bins, y = GC_content, fill = Classification, shape = taxon))+
  geom_point(size = 4)+
  theme_bw()+
  ylim(0,65)+
  theme(axis.text.x = element_text(angle = 60, hjust = 1),
        axis.text=element_text(size=14), axis.title=element_text(size=20),
        title=element_text(size=20), legend.text=element_text(size=16))+
  scale_fill_brewer(palette = "Accent")+
  scale_shape_manual(values = c(21,22,23,24))

grid_arrange_shared_legend(p1, p2)
grid_arrange_shared_legend(p4, p5)
```

